server {
    listen 80;
    server_name localhost;

    # Localização da build estática do Flutter Web
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Habilitar suporte a roteamento de Single Page Applications (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Tratamento de erros
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
